# Generated by Django 5.1.6 on 2025-02-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
